[book]
title = "Saluton Specification"
description = "The specification for Saluton"
authors = ["Max Walters"]
language = "en"
multilingual = false

[rust]
edition = "2021"

[output.html]
site-url = "/saluton/spec/"
